/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Actors.*;
import File.Manager.FileManager;
import training.center.TrainingCenter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author BinLaden
 */
public class AdminFrame extends javax.swing.JFrame {

    Admin Admin;

    public AdminFrame() {
        initComponents();

    }

    public AdminFrame(Admin Admin) {
        initComponents();
        this.Admin = Admin;
        WelcomeMessage.setText("Welcome Admin " + Admin.getFullName() + " !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ListCoursesPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        AddStudentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EditCoursePanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AddTutorPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NewCoursePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DeleteCoursePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ContainerCard = new javax.swing.JPanel();
        WelcomeCard = new javax.swing.JPanel();
        WelcomeMessage = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AddStudentCard = new javax.swing.JPanel();
        sUsernameField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sPasswordField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        sFullnameField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnAddStudent = new javax.swing.JButton();
        sIDField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        AddTutorCard = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        tUsernameField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        tPasswordField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        tFullnameField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        tSalaryField = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        btnAddTutor = new javax.swing.JButton();
        NewCourseCard = new javax.swing.JPanel();
        btnAddCourse = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        cCourseNameField = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        cCoursePriceField = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        cCourseHoursField = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        EditCourseCard = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        cCourseNewNameField = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        cCourseNewPriceField = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        cCourseNewHoursField = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        CoursesListBox = new javax.swing.JComboBox<>();
        cCourseNewTutorField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        DeleteCourseCard = new javax.swing.JPanel();
        CoursesListBoxDelete = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        ListCoursesCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 58, 73));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListCoursesPanel.setBackground(new java.awt.Color(30, 36, 45));
        ListCoursesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListCoursesPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        ListCoursesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListCoursesPanelMouseClicked(evt);
            }
        });
        ListCoursesPanel.setLayout(new java.awt.BorderLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_List_15px.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(45, 15));
        ListCoursesPanel.add(jLabel11, java.awt.BorderLayout.LINE_START);

        jLabel12.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("  List All Courses");
        ListCoursesPanel.add(jLabel12, java.awt.BorderLayout.CENTER);

        jPanel1.add(ListCoursesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 290, 50));

        AddStudentPanel.setBackground(new java.awt.Color(30, 36, 45));
        AddStudentPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddStudentPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        AddStudentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddStudentPanelMouseClicked(evt);
            }
        });
        AddStudentPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Add_User_Male_15px_2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(45, 15));
        AddStudentPanel.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel2.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Student");
        AddStudentPanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(AddStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 50));

        EditCoursePanel.setBackground(new java.awt.Color(30, 36, 45));
        EditCoursePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditCoursePanel.setPreferredSize(new java.awt.Dimension(0, 0));
        EditCoursePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditCoursePanelMouseClicked(evt);
            }
        });
        EditCoursePanel.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(0, 0));
        EditCoursePanel.add(jPanel8, java.awt.BorderLayout.CENTER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Edit_Property_15px.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(45, 15));
        EditCoursePanel.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jLabel8.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Edit Course");
        EditCoursePanel.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel1.add(EditCoursePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, 50));

        AddTutorPanel.setBackground(new java.awt.Color(30, 36, 45));
        AddTutorPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddTutorPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        AddTutorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddTutorPanelMouseClicked(evt);
            }
        });
        AddTutorPanel.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Add_Administrator_15px.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(45, 15));
        AddTutorPanel.add(jLabel3, java.awt.BorderLayout.LINE_START);

        jLabel4.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Tutor");
        AddTutorPanel.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(AddTutorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, 50));

        NewCoursePanel.setBackground(new java.awt.Color(30, 36, 45));
        NewCoursePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewCoursePanel.setPreferredSize(new java.awt.Dimension(0, 0));
        NewCoursePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewCoursePanelMouseClicked(evt);
            }
        });
        NewCoursePanel.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Form_15px_1.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(45, 15));
        NewCoursePanel.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jLabel6.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("New Course");
        NewCoursePanel.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(NewCoursePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 290, 50));

        DeleteCoursePanel.setBackground(new java.awt.Color(30, 36, 45));
        DeleteCoursePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteCoursePanel.setPreferredSize(new java.awt.Dimension(0, 0));
        DeleteCoursePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteCoursePanelMouseClicked(evt);
            }
        });
        DeleteCoursePanel.setLayout(new java.awt.BorderLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Delete_15px.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(45, 15));
        DeleteCoursePanel.add(jLabel9, java.awt.BorderLayout.LINE_START);

        jLabel14.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Delete Course");
        DeleteCoursePanel.add(jLabel14, java.awt.BorderLayout.CENTER);

        jPanel1.add(DeleteCoursePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 290, 50));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("User: Admin");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 40));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Name:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, 40));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 690));

        ContainerCard.setBackground(new java.awt.Color(110, 89, 222));
        ContainerCard.setPreferredSize(new java.awt.Dimension(0, 0));
        ContainerCard.setLayout(new java.awt.CardLayout());

        WelcomeCard.setBackground(new java.awt.Color(255, 0, 51));
        WelcomeCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeMessage.setFont(new java.awt.Font("Futura Md BT", 0, 24)); // NOI18N
        WelcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeCard.add(WelcomeMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 560, 170));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Manager_100px_1.png"))); // NOI18N
        WelcomeCard.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, 170));

        ContainerCard.add(WelcomeCard, "card2");

        AddStudentCard.setBackground(new java.awt.Color(236, 240, 241));
        AddStudentCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sUsernameField.setBackground(new java.awt.Color(236, 240, 241));
        sUsernameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sUsernameField.setForeground(new java.awt.Color(0, 102, 102));
        sUsernameField.setBorder(null);
        AddStudentCard.add(sUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 270, 30));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Fullname:");
        AddStudentCard.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, 20));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Username:");
        AddStudentCard.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, 20));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Password:");
        AddStudentCard.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        AddStudentCard.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 270, 10));

        sPasswordField.setBackground(new java.awt.Color(236, 240, 241));
        sPasswordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sPasswordField.setForeground(new java.awt.Color(0, 102, 102));
        sPasswordField.setBorder(null);
        AddStudentCard.add(sPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 270, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator4.setForeground(new java.awt.Color(0, 102, 102));
        AddStudentCard.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 270, 10));

        sFullnameField.setBackground(new java.awt.Color(236, 240, 241));
        sFullnameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sFullnameField.setForeground(new java.awt.Color(0, 102, 102));
        sFullnameField.setBorder(null);
        AddStudentCard.add(sFullnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 270, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator5.setForeground(new java.awt.Color(0, 102, 102));
        AddStudentCard.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 270, 10));

        btnAddStudent.setBackground(new java.awt.Color(0, 51, 102));
        btnAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStudent.setText("Add Student");
        btnAddStudent.setBorder(null);
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        AddStudentCard.add(btnAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 150, 50));

        sIDField.setBackground(new java.awt.Color(236, 240, 241));
        sIDField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sIDField.setForeground(new java.awt.Color(0, 102, 102));
        sIDField.setBorder(null);
        AddStudentCard.add(sIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 270, 30));

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("ID:");
        AddStudentCard.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 102));
        AddStudentCard.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 270, 10));

        ContainerCard.add(AddStudentCard, "card2");

        AddTutorCard.setBackground(new java.awt.Color(236, 240, 241));
        AddTutorCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        AddTutorCard.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 182, 270, 0));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Username:");
        AddTutorCard.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, 20));

        tUsernameField.setBackground(new java.awt.Color(236, 240, 241));
        tUsernameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tUsernameField.setForeground(new java.awt.Color(0, 102, 102));
        tUsernameField.setBorder(null);
        AddTutorCard.add(tUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 270, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator3.setForeground(new java.awt.Color(0, 102, 102));
        AddTutorCard.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 270, 10));

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Password:");
        AddTutorCard.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, 20));

        tPasswordField.setBackground(new java.awt.Color(236, 240, 241));
        tPasswordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tPasswordField.setForeground(new java.awt.Color(0, 102, 102));
        tPasswordField.setBorder(null);
        AddTutorCard.add(tPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 270, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator6.setForeground(new java.awt.Color(0, 102, 102));
        AddTutorCard.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 270, 10));

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Fullname:");
        AddTutorCard.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, 20));

        tFullnameField.setBackground(new java.awt.Color(236, 240, 241));
        tFullnameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tFullnameField.setForeground(new java.awt.Color(0, 102, 102));
        tFullnameField.setBorder(null);
        AddTutorCard.add(tFullnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 270, 30));

        jSeparator7.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator7.setForeground(new java.awt.Color(0, 102, 102));
        AddTutorCard.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 270, 10));

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Salary:");
        AddTutorCard.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, 30));

        tSalaryField.setBackground(new java.awt.Color(236, 240, 241));
        tSalaryField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tSalaryField.setForeground(new java.awt.Color(0, 102, 102));
        tSalaryField.setBorder(null);
        AddTutorCard.add(tSalaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 270, 30));

        jSeparator10.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator10.setForeground(new java.awt.Color(0, 102, 102));
        AddTutorCard.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 270, 10));

        btnAddTutor.setBackground(new java.awt.Color(0, 51, 102));
        btnAddTutor.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTutor.setText("Add Tutor");
        btnAddTutor.setBorder(null);
        btnAddTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTutorActionPerformed(evt);
            }
        });
        AddTutorCard.add(btnAddTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 150, 50));

        ContainerCard.add(AddTutorCard, "card2");

        NewCourseCard.setBackground(new java.awt.Color(236, 240, 241));
        NewCourseCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddCourse.setBackground(new java.awt.Color(0, 51, 102));
        btnAddCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCourse.setText("Add Course");
        btnAddCourse.setBorder(null);
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });
        NewCourseCard.add(btnAddCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 150, 50));

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Name:");
        NewCourseCard.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 20));

        cCourseNameField.setBackground(new java.awt.Color(236, 240, 241));
        cCourseNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cCourseNameField.setForeground(new java.awt.Color(255, 255, 255));
        cCourseNameField.setBorder(null);
        NewCourseCard.add(cCourseNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 270, 30));

        jSeparator14.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator14.setForeground(new java.awt.Color(0, 102, 102));
        NewCourseCard.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 270, 10));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Price:");
        NewCourseCard.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 20));

        cCoursePriceField.setBackground(new java.awt.Color(236, 240, 241));
        cCoursePriceField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cCoursePriceField.setForeground(new java.awt.Color(255, 255, 255));
        cCoursePriceField.setBorder(null);
        NewCourseCard.add(cCoursePriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 270, 30));

        jSeparator20.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator20.setForeground(new java.awt.Color(0, 102, 102));
        NewCourseCard.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 270, 10));

        jLabel36.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("Hours:");
        NewCourseCard.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 20));

        cCourseHoursField.setBackground(new java.awt.Color(236, 240, 241));
        cCourseHoursField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cCourseHoursField.setForeground(new java.awt.Color(255, 255, 255));
        cCourseHoursField.setBorder(null);
        NewCourseCard.add(cCourseHoursField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 270, 30));

        jSeparator21.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator21.setForeground(new java.awt.Color(0, 102, 102));
        NewCourseCard.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 270, 10));

        ContainerCard.add(NewCourseCard, "card2");

        EditCourseCard.setBackground(new java.awt.Color(236, 240, 241));
        EditCourseCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 51, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Save");
        jButton4.setToolTipText("");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        EditCourseCard.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 150, 50));

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("New Name:");
        EditCourseCard.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 20));

        cCourseNewNameField.setBackground(new java.awt.Color(236, 240, 241));
        cCourseNewNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cCourseNewNameField.setForeground(new java.awt.Color(255, 255, 255));
        cCourseNewNameField.setBorder(null);
        EditCourseCard.add(cCourseNewNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 270, 30));

        jSeparator15.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator15.setForeground(new java.awt.Color(0, 102, 102));
        EditCourseCard.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 270, 10));

        jLabel39.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("New Price:");
        EditCourseCard.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 20));

        cCourseNewPriceField.setBackground(new java.awt.Color(236, 240, 241));
        cCourseNewPriceField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cCourseNewPriceField.setForeground(new java.awt.Color(255, 255, 255));
        cCourseNewPriceField.setBorder(null);
        EditCourseCard.add(cCourseNewPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 270, 30));

        jSeparator24.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator24.setForeground(new java.awt.Color(0, 102, 102));
        EditCourseCard.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 270, 10));

        jLabel40.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("New Hours:");
        EditCourseCard.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 20));

        cCourseNewHoursField.setBackground(new java.awt.Color(236, 240, 241));
        cCourseNewHoursField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cCourseNewHoursField.setForeground(new java.awt.Color(255, 255, 255));
        cCourseNewHoursField.setBorder(null);
        EditCourseCard.add(cCourseNewHoursField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 270, 30));

        jSeparator25.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator25.setForeground(new java.awt.Color(0, 102, 102));
        EditCourseCard.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 270, 10));

        CoursesListBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course Name Example" }));
        EditCourseCard.add(CoursesListBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 390, -1));

        cCourseNewTutorField.setBackground(new java.awt.Color(236, 240, 241));
        cCourseNewTutorField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cCourseNewTutorField.setForeground(new java.awt.Color(255, 255, 255));
        cCourseNewTutorField.setBorder(null);
        EditCourseCard.add(cCourseNewTutorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 270, 30));

        jLabel41.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 51));
        jLabel41.setText("New Tutor:");
        EditCourseCard.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, 30));

        jSeparator26.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator26.setForeground(new java.awt.Color(0, 102, 102));
        EditCourseCard.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 270, 10));

        ContainerCard.add(EditCourseCard, "card2");

        DeleteCourseCard.setBackground(new java.awt.Color(236, 240, 241));
        DeleteCourseCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoursesListBoxDelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course Name Example" }));
        DeleteCourseCard.add(CoursesListBoxDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 390, 60));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Delete Course");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        DeleteCourseCard.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 390, 50));

        ContainerCard.add(DeleteCourseCard, "card2");

        ListCoursesCard.setBackground(new java.awt.Color(236, 240, 241));
        ListCoursesCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ContainerCard.add(ListCoursesCard, "card2");

        jPanel3.add(ContainerCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 760, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed

        try {
            Student newStudent = new Student();
            int ID = Integer.parseInt(sIDField.getText());
            newStudent.setUserName(sUsernameField.getText());
            newStudent.setPassWord(sPasswordField.getText());
            newStudent.setFullName(sFullnameField.getText());
            newStudent.setGrades(0);
            newStudent.setInvoices(0);
            newStudent.setAttendance(0);
            newStudent.setID(ID);
            this.Admin.addStudent(
                    newStudent.getID(),
                    newStudent.getUserName(),
                    newStudent.getPassword(),
                    newStudent.getInvoices(),
                    newStudent.getFullName()
            );
            Tutor t = new Tutor();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter ID as a number!");
        }

    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void AddStudentPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStudentPanelMouseClicked
        // TODO add your handling code here:
        ContainerCard.removeAll();
        ContainerCard.repaint();
        ContainerCard.revalidate();
        ContainerCard.add(AddStudentCard);
        ContainerCard.repaint();
        ContainerCard.revalidate();
        AddTutorPanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        NewCoursePanel.setBackground(new Color(30, 36, 45));
        EditCoursePanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        DeleteCoursePanel.setBackground(new Color(30, 36, 45));
        AddStudentPanel.setBackground(new Color(255, 51, 102));

    }//GEN-LAST:event_AddStudentPanelMouseClicked

    private void AddTutorPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTutorPanelMouseClicked
        // TODO add your handling code here:
        ContainerCard.removeAll();
        ContainerCard.repaint();
        ContainerCard.revalidate();
        ContainerCard.add(AddTutorCard);
        ContainerCard.repaint();
        ContainerCard.revalidate();
        AddStudentPanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        NewCoursePanel.setBackground(new Color(30, 36, 45));
        EditCoursePanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        DeleteCoursePanel.setBackground(new Color(30, 36, 45));
        AddTutorPanel.setBackground(new Color(255, 51, 102));
    }//GEN-LAST:event_AddTutorPanelMouseClicked

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        try {
            // TODO add your handling code here:
            float CoursePrice = Float.parseFloat(cCoursePriceField.getText());
            int CourseHours = Integer.parseInt(cCourseHoursField.getText());
            this.Admin.AddCourse(cCourseNameField.getText(), CoursePrice, CourseHours);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter Price and Hours as numbers");
        }
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void NewCoursePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewCoursePanelMouseClicked
        // TODO add your handling code here:
        ContainerCard.removeAll();
        ContainerCard.repaint();
        ContainerCard.revalidate();
        ContainerCard.add(NewCourseCard);
        ContainerCard.repaint();
        ContainerCard.revalidate();
        AddStudentPanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        AddTutorPanel.setBackground(new Color(30, 36, 45));
        EditCoursePanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        DeleteCoursePanel.setBackground(new Color(30, 36, 45));
        NewCoursePanel.setBackground(new Color(255, 51, 102));
    }//GEN-LAST:event_NewCoursePanelMouseClicked

    private void EditCoursePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditCoursePanelMouseClicked
        try {
            // TODO add your handling code here:
            ContainerCard.removeAll();
            ContainerCard.repaint();
            ContainerCard.revalidate();
            ContainerCard.add(EditCourseCard);
            ContainerCard.repaint();
            ContainerCard.revalidate();
            AddStudentPanel.setBackground(new Color(30, 36, 45));
            ListCoursesPanel.setBackground(new Color(30, 36, 45));
            AddTutorPanel.setBackground(new Color(30, 36, 45));
            DeleteCoursePanel.setBackground(new Color(30, 36, 45));
            ListCoursesPanel.setBackground(new Color(30, 36, 45));
            NewCoursePanel.setBackground(new Color(30, 36, 45));
            EditCoursePanel.setBackground(new Color(255, 51, 102));
            CoursesListBox.removeAllItems();
            Courses c = new Courses();
            for (int i = 0; i < c.loadcourse().size(); i++) {
                CoursesListBox.addItem(c.loadcourse().get(i).getCourseName());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EditCoursePanelMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            String OldName = CoursesListBox.getSelectedItem().toString();
            double newPrice = Double.parseDouble(cCourseNewPriceField.getText());
            int newHours = Integer.parseInt(cCourseNewHoursField.getText());
            this.Admin.UpdateCourse(OldName, cCourseNewNameField.getText(), newPrice, newHours, cCourseNewTutorField.getText());
            //this.Admin.UpdateCourse(, name, ERROR, ABORT, teacher);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter New Price and New Hours as numbers");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void DeleteCoursePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteCoursePanelMouseClicked
        // TODO add your handling code here:
        ContainerCard.removeAll();
        ContainerCard.repaint();
        ContainerCard.revalidate();
        ContainerCard.add(DeleteCourseCard);
        ContainerCard.repaint();
        ContainerCard.revalidate();
        AddStudentPanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        AddTutorPanel.setBackground(new Color(30, 36, 45));
        EditCoursePanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        NewCoursePanel.setBackground(new Color(30, 36, 45));
        DeleteCoursePanel.setBackground(new Color(255, 51, 102));
        try {
            CoursesListBoxDelete.removeAllItems();
            // TODO add your handling code here:
            Courses c = new Courses();
            for (int i = 0; i < c.loadcourse().size(); i++) {
                CoursesListBoxDelete.addItem(c.loadcourse().get(i).getCourseName());
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No Courses Have Been Made Yet!");
        }
    }//GEN-LAST:event_DeleteCoursePanelMouseClicked

    private void ListCoursesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListCoursesPanelMouseClicked
        // TODO add your handling code here:
        ContainerCard.removeAll();
        ContainerCard.repaint();
        ContainerCard.revalidate();
        ContainerCard.add(ListCoursesCard);
        ContainerCard.repaint();
        ContainerCard.revalidate();
        AddStudentPanel.setBackground(new Color(30, 36, 45));
        AddTutorPanel.setBackground(new Color(30, 36, 45));
        EditCoursePanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        NewCoursePanel.setBackground(new Color(30, 36, 45));
        DeleteCoursePanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(255, 51, 102));
    }//GEN-LAST:event_ListCoursesPanelMouseClicked

    private void btnAddTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTutorActionPerformed
        try {
            // TODO add your handling code here:
            Float Salary = Float.parseFloat(tSalaryField.getText());
            Tutor newTutor = new Tutor();
            this.Admin.addTutor(tFullnameField.getText(), tPasswordField.getText(), Salary, tUsernameField.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter Salary as a number!");
        }
    }//GEN-LAST:event_btnAddTutorActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            this.Admin.DeleteCourse(CoursesListBoxDelete.getSelectedItem().toString());
            CoursesListBoxDelete.removeAllItems();
            // TODO add your handling code here:
            Courses c = new Courses();
            for (int i = 0; i < c.loadcourse().size(); i++) {
                CoursesListBoxDelete.addItem(c.loadcourse().get(i).getCourseName());
            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No Courses to Delete");
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No Courses to Delete");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddStudentCard;
    private javax.swing.JPanel AddStudentPanel;
    private javax.swing.JPanel AddTutorCard;
    private javax.swing.JPanel AddTutorPanel;
    private javax.swing.JPanel ContainerCard;
    private javax.swing.JComboBox<String> CoursesListBox;
    private javax.swing.JComboBox<String> CoursesListBoxDelete;
    private javax.swing.JPanel DeleteCourseCard;
    private javax.swing.JPanel DeleteCoursePanel;
    private javax.swing.JPanel EditCourseCard;
    private javax.swing.JPanel EditCoursePanel;
    private javax.swing.JPanel ListCoursesCard;
    private javax.swing.JPanel ListCoursesPanel;
    private javax.swing.JPanel NewCourseCard;
    private javax.swing.JPanel NewCoursePanel;
    private javax.swing.JPanel WelcomeCard;
    private javax.swing.JLabel WelcomeMessage;
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAddTutor;
    private javax.swing.JTextField cCourseHoursField;
    private javax.swing.JTextField cCourseNameField;
    private javax.swing.JTextField cCourseNewHoursField;
    private javax.swing.JTextField cCourseNewNameField;
    private javax.swing.JTextField cCourseNewPriceField;
    private javax.swing.JTextField cCourseNewTutorField;
    private javax.swing.JTextField cCoursePriceField;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField sFullnameField;
    private javax.swing.JTextField sIDField;
    private javax.swing.JTextField sPasswordField;
    private javax.swing.JTextField sUsernameField;
    private javax.swing.JTextField tFullnameField;
    private javax.swing.JTextField tPasswordField;
    private javax.swing.JTextField tSalaryField;
    private javax.swing.JTextField tUsernameField;
    // End of variables declaration//GEN-END:variables
}
