/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Actors.*;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import Actors.*;
import java.awt.Color;
import java.io.IOException;

/**
 *
 * @author BinLaden
 */
public class TutorFrame extends javax.swing.JFrame {

    Tutor Tutor;

    /**
     * Creates new form TutorFrame
     */
    public TutorFrame() throws FileNotFoundException {
        initComponents();
    }

    public TutorFrame(Tutor Tutor) throws FileNotFoundException {
        initComponents();
        jLabel4.setText("Cheers " + Tutor.getFullName());
        this.Tutor = Tutor;
        Courses c = new Courses();
        for (int i = 0; i < c.loadcourse().size(); i++) {
            CoursesList.addItem(c.loadcourse().get(i).getCourseName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AddCoursePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListCoursesPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DeleteCoursePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ContainerCard = new javax.swing.JPanel();
        WelcomeCard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddCourseCard = new javax.swing.JPanel();
        CoursesList = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        ListCoursesCard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DeleteCourseCard = new javax.swing.JPanel();
        TeachingCoursesList = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(48, 58, 73));
        jPanel2.setMinimumSize(new java.awt.Dimension(260, 460));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddCoursePanel.setBackground(new java.awt.Color(30, 36, 45));
        AddCoursePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddCoursePanel.setPreferredSize(new java.awt.Dimension(0, 0));
        AddCoursePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCoursePanelMouseClicked(evt);
            }
        });
        AddCoursePanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Plus_Math_15px_2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(45, 15));
        AddCoursePanel.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel2.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Course");
        AddCoursePanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.add(AddCoursePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 330, 50));

        ListCoursesPanel.setBackground(new java.awt.Color(30, 36, 45));
        ListCoursesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListCoursesPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        ListCoursesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListCoursesPanelMouseClicked(evt);
            }
        });
        ListCoursesPanel.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_List_15px.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(45, 15));
        ListCoursesPanel.add(jLabel9, java.awt.BorderLayout.LINE_START);

        jLabel10.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("List Courses");
        ListCoursesPanel.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel2.add(ListCoursesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 330, 50));

        DeleteCoursePanel.setBackground(new java.awt.Color(30, 36, 45));
        DeleteCoursePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteCoursePanel.setPreferredSize(new java.awt.Dimension(0, 0));
        DeleteCoursePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteCoursePanelMouseClicked(evt);
            }
        });
        DeleteCoursePanel.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Delete_15px.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(45, 15));
        DeleteCoursePanel.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jLabel8.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Delete Course");
        DeleteCoursePanel.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel2.add(DeleteCoursePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, 50));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User: Admin");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 220, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 640));

        ContainerCard.setBackground(new java.awt.Color(110, 89, 222));
        ContainerCard.setPreferredSize(new java.awt.Dimension(0, 0));
        ContainerCard.setLayout(new java.awt.CardLayout());

        WelcomeCard.setBackground(new java.awt.Color(30, 36, 45));
        WelcomeCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Salute_100px.png"))); // NOI18N
        WelcomeCard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 100, 120));

        jLabel4.setFont(new java.awt.Font("Lobster 1.3", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 95, 129));
        jLabel4.setText("Cheers");
        WelcomeCard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 370, 60));

        ContainerCard.add(WelcomeCard, "card2");

        AddCourseCard.setBackground(new java.awt.Color(236, 240, 241));
        AddCourseCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoursesList.setBackground(new java.awt.Color(0, 204, 204));
        CoursesList.setBorder(null);
        AddCourseCard.add(CoursesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 390, 40));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setForeground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Add Course");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        AddCourseCard.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 390, 40));

        ContainerCard.add(AddCourseCard, "card2");

        ListCoursesCard.setBackground(new java.awt.Color(236, 240, 241));
        ListCoursesCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        jTable1.setBackground(new java.awt.Color(0, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Price", "Hours"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);

        ListCoursesCard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 450, 100));

        ContainerCard.add(ListCoursesCard, "card2");

        DeleteCourseCard.setBackground(new java.awt.Color(236, 240, 241));
        DeleteCourseCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeleteCourseCard.add(TeachingCoursesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 390, 50));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Delete Course");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        DeleteCourseCard.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 390, 50));

        ContainerCard.add(DeleteCourseCard, "card2");

        jPanel1.add(ContainerCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 0, 740, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1079, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddCoursePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCoursePanelMouseClicked
        // TODO add your handling code here:
        ContainerCard.removeAll();
        ContainerCard.repaint();
        ContainerCard.revalidate();
        ContainerCard.add(AddCourseCard);
        ContainerCard.repaint();
        ContainerCard.revalidate();
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        DeleteCoursePanel.setBackground(new Color(30, 36, 45));
        AddCoursePanel.setBackground(new Color(255, 51, 102));
        CoursesList.removeAllItems();

        try {
            Courses c = new Courses();
            for (int i = 0; i < c.loadcourse().size(); i++) {
                CoursesList.addItem(c.loadcourse().get(i).getCourseName());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TutorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddCoursePanelMouseClicked

    private void ListCoursesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListCoursesPanelMouseClicked
        // TODO add your handling code here:
        ContainerCard.removeAll();
        ContainerCard.repaint();
        ContainerCard.revalidate();
        ContainerCard.add(ListCoursesCard);
        ContainerCard.repaint();
        ContainerCard.revalidate();
        AddCoursePanel.setBackground(new Color(30, 36, 45));
        DeleteCoursePanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(255, 51, 102));
        try {
            ArrayList<Courses> CoursesList = this.Tutor.ListCourse();
        } catch (IOException ex) {
            Logger.getLogger(TutorFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TutorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ListCoursesPanelMouseClicked

    private void DeleteCoursePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteCoursePanelMouseClicked
        // TODO add your handling code here:
        ContainerCard.removeAll();
        ContainerCard.repaint();
        ContainerCard.revalidate();
        ContainerCard.add(DeleteCourseCard);
        ContainerCard.repaint();
        ContainerCard.revalidate();
        AddCoursePanel.setBackground(new Color(30, 36, 45));
        ListCoursesPanel.setBackground(new Color(30, 36, 45));
        DeleteCoursePanel.setBackground(new Color(255, 51, 102));
        TeachingCoursesList.removeAllItems();
        ArrayList<Courses> TeachingCourses = new ArrayList<Courses>();
        TeachingCourses = this.Tutor.getTeachingCourses();
        for (int i = 0; i < TeachingCourses.size(); i++) {
            TeachingCoursesList.addItem(TeachingCourses.get(i).getCourseName());
        }

    }//GEN-LAST:event_DeleteCoursePanelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            this.Tutor.DeleteCourse(TeachingCoursesList.getSelectedItem().toString());
            ArrayList<Courses> TeachingCourses = new ArrayList<Courses>();
            TeachingCourses = this.Tutor.getTeachingCourses();
            for (int i = 0; i < TeachingCourses.size(); i++) {
                TeachingCoursesList.removeAllItems();
                TeachingCoursesList.addItem(TeachingCourses.get(i).getCourseName());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TutorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String SelectedCourse = CoursesList.getSelectedItem().toString();
            this.Tutor.AddCourse(SelectedCourse);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(TutorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TutorFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TutorFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddCourseCard;
    private javax.swing.JPanel AddCoursePanel;
    private javax.swing.JPanel ContainerCard;
    private javax.swing.JComboBox<String> CoursesList;
    private javax.swing.JPanel DeleteCourseCard;
    private javax.swing.JPanel DeleteCoursePanel;
    private javax.swing.JPanel ListCoursesCard;
    private javax.swing.JPanel ListCoursesPanel;
    private javax.swing.JComboBox<String> TeachingCoursesList;
    private javax.swing.JPanel WelcomeCard;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
